name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [workflow_dispatch]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Extract repository parts
        run: |
          repository=$GITHUB_REPOSITORY
          owner=${repository%/*}
          repo=${repository#*/}
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "Owner: $owner"
          echo "Repository: $repo"
          echo "lower-repo: ${repo,,}"
